def imageTag = "unknown"

// This is based on the CI workflow from .github/workflows/ci.yaml

pipeline {
    agent {
        kubernetes {
            cloud 'internal'
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: git
    image: alpine/git:v2.26.2
    command: ['cat']
    tty: true
  - name: golang
    image: golang:1.16-buster
    command: ['cat']
    tty: true
  - name: kaniko
    image: kaniko-project/executor:debug
    command: ['/busybox/cat']
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  - name: postgres
    image: postgres:10.8
    ports:
      - name: postgres
        containerPort: 5432
  - name: mysql
    image: mysql:5.7
    ports:
      - name: mysql
        containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: root
      - name: MYSQL_DATABASE
        value: dex
  - name: etcd
    image: gcr.io/etcd-development/etcd:v3.2.9
    ports:
      - name: etcd
        containerPort: 2379
    env:
      - name: ETCD_LISTEN_CLIENT_URLS
        value: http://0.0.0.0:2379
      - name: ETCD_ADVERTISE_CLIENT_URLS
        value: http://0.0.0.0:2379
  - name: keystone
    image: openio/openstack-keystone:pike
    ports:
      - name: keystone
        containerPort: 5000
      - name: keystone-admin
        containerPort: 35357
  - name: openldap
    image: osixia/openldap:1.4.0
    command:
      - "/bin/sh"
      - "-c"
      - "mkfifo /tmp/start; cat /tmp/start; exec /container/tool/run --copy-service"
    env:
      - name: LDAP_BASE_DN
        value: "dc=example,dc=org"
      - name: LDAP_TLS
        value: "true"
      - name: LDAP_TLS_VERIFY_CLIENT
        value: "try"
    ports:
      - name: ldap
        containerPort: 389
      - name: ldaps
        containerPort: 636
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
"""
        }
    }
    options {
        timeout(time: 15, unit: 'MINUTES', activity: true)
	    disableConcurrentBuilds()
	    buildDiscarder(logRotator(numToKeepStr: '20'))
	    timestamps()
	    skipDefaultCheckout()
	    ansiColor('xterm')
    }
    triggers {
	    pollSCM('H/5 * * * *')
    }

    stages {
        stage ('Checkout') {
            steps {
		        container('git') {
		            checkout scm
		            script {
			            imageTag = sh(returnStdout: true,
				                      script: "git describe --tags --match 'v*.*.*'").trim()
			            currentBuild.displayName = imageTag
			            echo "Building dex:${imageTag}"
		            }
		        }
            }
        }

        stage ('Start LDAP') {
            steps {
                container('openldap') {
                    sh 'cp -r connector/ldap/testdata/certs /container/service/slapd/assets/'
                    sh 'cp connector/ldap/testdata/schema.ldif /container/service/slapd/assets/config/bootstrap/ldif/99-schema.ldif'
                    sh 'echo "Starting LDAP" > /tmp/start '
                    sh 'while ! ldapwhoami -D cn=admin,dc=example,dc=org -w admin; do sleep 1; done'
                }
            }
        }

        stage ('Test') {
            environment {
                DEX_MYSQL_DATABASE = 'dex'
                DEX_MYSQL_USER = 'root'
                DEX_MYSQL_PASSWORD = 'root'
                DEX_MYSQL_HOST = '127.0.0.1'
                DEX_MYSQL_PORT = '3306'
                DEX_POSTGRES_DATABASE = 'postgres'
                DEX_POSTGRES_USER = 'postgres'
                DEX_POSTGRES_PASSWORD = 'postgres'
                DEX_POSTGRES_HOST = 'localhost'
                DEX_POSTGRES_PORT = '5432'
                DEX_ETCD_ENDPOINTS = 'http://localhost:2379'
                DEX_LDAP_HOST = 'localhost'
                DEX_LDAP_PORT = '389'
                DEX_LDAP_TLS_PORT = '636'
                DEX_KEYSTONE_URL = 'http://localhost:5000'
                DEX_KEYSTONE_DAMIN_URL = 'http://localhost:35357'
                DEX_KEYSTONE_ADMIN_USER = 'demo'
                DEX_KEYSTONE_ADMIN_PASS = 'DEMO_PASS'
            }
            steps {
                // Now run the tests
                container('golang') {
                    sh 'make testall'
                }
            }
            post {
                always {
                    script {
                        sh 'mkdir -p logs'
                        logData = containerLog(name: 'postgres', returnLog: true)
                        writeFile(file: 'logs/postgres.log', text: logData)
                        logData = containerLog(name: 'mysql', returnLog: true)
                        writeFile(file: 'logs/mysql.log', text: logData)
                        logData = containerLog(name: 'etcd', returnLog: true)
                        writeFile(file: 'logs/etcd.log', text: logData)
                        logData = containerLog(name: 'keystone', returnLog: true)
                        writeFile(file: 'logs/keystone.log', text: logData)
                        logData = containerLog(name: 'openldap', returnLog: true)
                        writeFile(file: 'logs/openldap.log', text: logData)
                    }

                    archiveArtifacts allowEmptyArchive: true, artifacts: 'logs/*.log', onlyIfSuccessful: false
                }
            }
        }

        stage ('Lint') {
            steps {
                container('golang') {
                    sh 'make lint'
                }
            }
        }

        stage ('Verify proto') {
            steps {
                container('golang') {
                    // verify-proto needs unzip
                    sh 'apt-get update && apt-get -y install unzip'
                    sh 'make verify-proto'
                }
            }
        }

        stage ('Build image') {
            steps {
		        container('kaniko') {
		            sh "/kaniko/executor -f Dockerfile -c `pwd` --destination=docker.worldprogramming.com/dex:${imageTag}"
		        }
	        }
        }
    }
}
